spawn:
  world: world
  x: 0.0
  y: 100.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0

player:
  sendToSpawnAtJoin: true
  enableCustomJoinMessage: true
  enableCustomQuitMessage: true
  gamemode: ADVENTURE
  canPvP: false
  isFallDamageEnabled: false
  isFoodLossEnabled: false
  levelOnJoin: 2026
  expOnJoin: 0.0
  playerMaxHealth: 20.0
  playerFoodLevel: 20

world:
  canWeatherChange: false
  canMobSpawn: false
  teleportToSpawnIfFall: true
  teleportIfYPosUnder: 5

permissions:
  block:
    break: "lobbymanager.block.break"
    place: "lobbymanager.block.place"
  commands:
    spawn: "lobbymanager.command.spawn"
    setSpawn: "lobbymanager.command.setspawn"
    reload: "lobbymanager.command.reload"